import Head from 'next/head'
import Header from '../components/header'
import Footer from '../components/footer'
import Main from '../components/Main'

export default function Home() {
	return (
		<div>
			<Head>
				<link rel="preconnect" href="https://fonts.googleapis.com"/>
				<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
				<link 
					href="https://fonts.googleapis.com/css2?family=Roboto+Slab&family=Roboto:ital,wght@1,500&display=swap"
					rel="stylesheet"
				/>
				<title>betterAmbience</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="https://i.imgur.com/CiSmn0s.png" />
			</Head>
			<Header/>
			<Main/>
			<Footer/>
		</div>
	)
}
